version: "3"
services:
  api:
    build:
      context: ./api
    container_name: dashboard-api
    ports:
      - "8000:8000"
    env_file:
      - ./api/src/.env
    restart: unless-stopped # Add this line to enable automatic restart

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_HSL_KEY=a1e437f79628464c9ea8d542db6f6e94
        - REACT_APP_HSL_STOP_ID_FIRST=HSL:1392136
        - REACT_APP_HSL_STOP_ID_SECOND=HSL:1402181
        - PORT=5000
        - REACT_APP_LOCAL_API_PORT=8000
        - REACT_APP_LOCAL_API_URL=http://dashboard-api
    container_name: dashboard-frontend
    tty: true
    ports:
      - "3000:5000"
    restart: unless-stopped # Add this line to enable automatic restart

  backend:
    build:
      context: ./backend
    container_name: dashboard-backend
    ports:
      - "8080:8080"
    environment:
      FRONTEND_PORT: 5000
      FRONTEND_URL: http://dashboard-frontend
      NODE_ENV: prod
    restart: unless-stopped # Add this line to enable automatic restart
